//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';

//Users
//Get All Users
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS';
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR';
export const ALLUSERS_LOADING = 'ALLUSERS_LOADING';
//User Update
export const UPDATEUSER_SUCCESS = 'UPDATEUSER_SUCCESS';
export const UPDATEUSER_ERROR = 'UPDATEUSER_ERROR';
//User Delete
export const DELETEUSER_SUCCESS = 'DELETEUSER_SUCCESS';
export const DELETEUSER_ERROR = 'DELETEUSER_ERROR';
//'User's Vehivle
export const USERVEHICLE_SUCCESS = 'USERVEHICLE_SUCCESS';
export const USERVEHICLE_ERROR = 'USERVEHICLE_ERROR';
export const USERVEHICLE_LOADING = 'USERVEHICLE_LOADING';

//vehicle
export const ALLVEHICLES_SUCCESS = 'ALLVEHICLES_SUCCESS';
export const ALLVEHICLES_ERROR = 'ALLVEHICLES_ERROR';
export const ALLVEHICLES_LOADING = 'ALLVEHICLES_LOADING';

export const DELETEVEHICLE_SUCCESS = 'DELETEVEHICLE_SUCCESS';
export const DELETEVEHICLE_ERROR = 'DELETEVEHICLE_ERROR';
export const DELETEVEHICLE_LOADING = 'DELETEVEHICLE_LOADING';

export const VEHICLEBYVEHICLEID_SUCCESS = 'VEHICLEBYVEHICLEID_SUCCESS';
export const VEHICLEBYVEHICLEID_ERROR = 'VEHICLEBYVEHICLEID_ERROR';
export const VEHICLEBYVEHICLEID_LOADING = 'VEHICLEBYVEHICLEID_LOADING';
//Update Vehicle
export const UPDATEVEHICLE_SUCCESS = 'UPDATEVEHICLE_SUCCESS';
export const UPDATEVEHICLE_ERROR = 'UPDATEVEHICLE_ERROR';

//service
export const ALLSERVICES_SUCCESS = 'ALLSERVICES_SUCCESS';
export const ALLSERVICES_ERROR = 'ALLSERVICES_ERROR';
export const ALLSERVICES_LOADING = 'ALLSERVICES_LOADING';
