//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';

//Users
//Get All Users
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS';
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR';
export const ALLUSERS_LOADING = 'ALLUSERS_LOADING';
//User Update
export const UPDATEUSER_SUCCESS = 'UPDATEUSER_SUCCESS';
export const UPDATEUSER_ERROR = 'UPDATEUSER_ERROR';
//User Delete
export const DELETEUSER_SUCCESS = 'DELETEUSER_SUCCESS';
export const DELETEUSER_ERROR = 'DELETEUSER_ERROR';
//'User's Vehivle
export const USERVEHICLE_SUCCESS = 'USERVEHICLE_SUCCESS';
export const USERVEHICLE_ERROR = 'USERVEHICLE_ERROR';
export const USERVEHICLE_LOADING = 'USERVEHICLE_LOADING';

//vehicle
export const ALLVEHICLES_SUCCESS = 'ALLVEHICLES_SUCCESS';
export const ALLVEHICLES_ERROR = 'ALLVEHICLES_ERROR';
export const ALLVEHICLES_LOADING = 'ALLVEHICLES_LOADING';

export const DELETEVEHICLE_SUCCESS = 'DELETEVEHICLE_SUCCESS';
export const DELETEVEHICLE_ERROR = 'DELETEVEHICLE_ERROR';
export const DELETEVEHICLE_LOADING = 'DELETEVEHICLE_LOADING';

//Update Vehicle
export const UPDATEVEHICLE_SUCCESS = 'UPDATEVEHICLE_SUCCESS';
export const UPDATEVEHICLE_ERROR = 'UPDATEVEHICLE_ERROR';

//service
export const ALLSERVICES_SUCCESS = 'ALLSERVICES_SUCCESS';
export const ALLSERVICES_ERROR = 'ALLSERVICES_ERROR';
export const ALLSERVICES_LOADING = 'ALLSERVICES_LOADING';

//service plans
export const ALLSERVICEPLANS_SUCCESS = 'ALLSERVICEPLANS_SUCCESS';
export const ALLSERVICEPLANS_ERROR = 'ALLSERVICEPLANS_ERROR';
export const ALLSERVICEPLANS_LOADING = 'ALLSERVICEPLANS_LOADING';

//getserviceplansbyid plans
export const GETSERVICEPRICEBYID_SUCCESS = 'GETSERVICEPRICEBYID_SUCCESS';
export const GETSERVICEPRICEBYID_ERROR = 'GETSERVICEPRICEBYID_ERROR';
export const GETSERVICEPRICEBYID_LOADING = 'GETSERVICEPRICEBYID_LOADING';

//service report
export const GETSERVICEREPORT_SUCCESS = 'GETSERVICEREPORT_SUCCESS';
export const GETSERVICEREPORT_ERROR = 'GETSERVICEREPORT_ERROR';
export const GETSERVICEREPORT_LOADING = 'GETSERVICEREPORT_LOADING';
export const GETSERVICEREPORTWITHFILTER_SUCCESS =
  'GETSERVICEREPORTWITHFILTER_SUCCESS';

//Vehicle Service Details
export const VEHICLESERVICEDETAILS_SUCCESS = 'VEHICLESERVICEDETAILS_SUCCESS';
export const VEHICLESERVICEDETAILS_ERROR = 'VEHICLESERVICEDETAILS_ERROR';
export const VEHICLESERVICEDETAILS_LOADING = 'VEHICLESERVICEDETAILS_LOADING';

//Vehicle Service Details Update
export const UPDATEVEHICLESERVICE_LOADING = 'UPDATEVEHICLESERVICE_LOADING';
export const UPDATEVEHICLESERVICE_SUCCESS = 'UPDATEVEHICLESERVICE_SUCCESS';
export const UPDATEVEHICLESERVICE_ERROR = 'UPDATEVEHICLESERVICE_ERROR';
//Dashboard
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
